In [1]:
#This is a Tic-Tac-Toe game
#Before going to the main frame of the game, there are 2 helper-functions

In [2]:
import numpy as np

In [3]:
#First helper-function
#Check whether the winning condition is meet on a certain game board
def check_result(game_board,player_no,size=3):
    trues=[True]*size
    #same numbers on horizontal row
    for i in range(size):
        if [game_board[i,j]==player_no for j in range(size)]==trues:
            return player_no
    #same numbers on vertical column
    for j in range(size):
        if [game_board[i,j]==player_no for i in range(size)]==trues:
            return player_no
    #same numbers on \diagonal
    if [game_board[i,i]==player_no for i in range(size)]==trues:
        return player_no
    #same numbers on /diagonal
    if [game_board[i,size-1-i]==player_no for i in range(size)]==trues:
        return player_no
    return 0

In [4]:
#Second helper-function
#Check whether a valid coordinate is inputed into the board
#A valid coordinate input is like 01,00,02,etc.
def get_input_(player_no,previous_inputs,size=3):
    while True:
        a=input("Player {} input: ".format(player_no))
        i=int(a[0])
        j=int(a[1])
        #if the input is outside the range of 0 to 2, input again
        if i in range(size) and j in range(size):
            #if a player input a position which is already filled, input again
            if a not in previous_inputs:
                return i,j,a

In [7]:
#main frame of the tic-tac-toe game function 
def tic_tac_toe(size=3):
    game_board=np.zeros((size,size))
    previous_inputs=[]
    print(game_board)
    for game_round in range(size**2):
        if game_round%2==0:
            player=1
        else:
            player=2
        p_input=get_input_(player,previous_inputs,size)
        previous_inputs.append(p_input[2])
        game_board[p_input[0],p_input[1]]=player
        print(game_board)
        if check_result(game_board,player,size)==player:
            print("Player {} wins".format(player))
            return player
    print("Draw")
    return 0

In [8]:
tic_tac_toe(3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Player 1 input:  01


[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Player 2 input:  11


[[0. 1. 0.]
 [0. 2. 0.]
 [0. 0. 0.]]


Player 1 input:  12


[[0. 1. 0.]
 [0. 2. 1.]
 [0. 0. 0.]]


Player 2 input:  00


[[2. 1. 0.]
 [0. 2. 1.]
 [0. 0. 0.]]


Player 1 input:  22


[[2. 1. 0.]
 [0. 2. 1.]
 [0. 0. 1.]]


Player 2 input:  02


[[2. 1. 2.]
 [0. 2. 1.]
 [0. 0. 1.]]


Player 1 input:  21


[[2. 1. 2.]
 [0. 2. 1.]
 [0. 1. 1.]]


Player 2 input:  20


[[2. 1. 2.]
 [0. 2. 1.]
 [2. 1. 1.]]
Player 2 wins


2

In [9]:
tic_tac_toe(4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Player 1 input:  00


[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Player 2 input:  02


[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Player 1 input:  11


[[1. 0. 2. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Player 2 input:  22


[[1. 0. 2. 0.]
 [0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 0.]]


Player 1 input:  21


[[1. 0. 2. 0.]
 [0. 1. 0. 0.]
 [0. 1. 2. 0.]
 [0. 0. 0. 0.]]


Player 2 input:  21
Player 2 input:  00
Player 2 input:  02
Player 2 input:  10


[[1. 0. 2. 0.]
 [2. 1. 0. 0.]
 [0. 1. 2. 0.]
 [0. 0. 0. 0.]]


Player 1 input:  01


[[1. 1. 2. 0.]
 [2. 1. 0. 0.]
 [0. 1. 2. 0.]
 [0. 0. 0. 0.]]


Player 2 input:  02
Player 2 input:  12


[[1. 1. 2. 0.]
 [2. 1. 2. 0.]
 [0. 1. 2. 0.]
 [0. 0. 0. 0.]]


Player 1 input:  31


[[1. 1. 2. 0.]
 [2. 1. 2. 0.]
 [0. 1. 2. 0.]
 [0. 1. 0. 0.]]
Player 1 wins


1