In [1]:
#This is a Tic-Tac-Toe game
#Before going to the main frame of the game, there are 2 helper-functions

In [2]:
import numpy as np

In [3]:
#First helper-function
#Check whether the winning condition is meet on a certain game board
def check_result(game_board,player_no):
    #same numbers on horizontal row
    for i in range(3):
        if [game_board[i,j]==player_no for j in range(3)]==[True,True,True]:
            return player_no
    #same numbers on vertical column
    for j in range(3):
        if [game_board[i,j]==player_no for i in range(3)]==[True,True,True]:
            return player_no
    #same numbers on \diagonal
    if [game_board[i,i]==player_no for i in range(3)]==[True,True,True]:
        return player_no
    #same numbers on /diagonal
    if [game_board[i,2-i]==player_no for i in range(3)]==[True,True,True]:
        return player_no
    return 0

In [4]:
#Second helper-function
#Check whether a valid coordinate is inputed into the board
#A valid coordinate input is like 01,00,02,etc.
def get_input_(player_no,previous_inputs):
    while True:
        a=input("Player {} input: ".format(player_no))
        i=int(a[0])
        j=int(a[1])
        #if the input is outside the range of 0 to 2, input again
        if i in range(3) and j in range(3):
            #if a player input a position which is already filled, input again
            if a not in previous_inputs:
                return i,j,a

In [5]:
#main frame of the tic-tac-toe game
game_board=np.zeros((3,3))
#The flag is for the result of the game, true is there is win or lose, false if there is draw
flag=False
previous_inputs=[]
print(game_board)
for game_round in range(9):
    if game_round%2==0:
        player=1
    else:
        player=2
    p_input=get_input_(player,previous_inputs)
    previous_inputs.append(p_input[2])
    game_board[p_input[0],p_input[1]]=player
    print(game_board)
    if check_result(game_board,player)==player:
        print("Player {} wins".format(player))
        flag=True
        break
if flag==False:
    print("Draw")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Player 1 input:  00


[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Player 2 input:  11


[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 0.]]


Player 1 input:  00
Player 1 input:  11
Player 1 input:  12


[[1. 0. 0.]
 [0. 2. 1.]
 [0. 0. 0.]]


Player 2 input:  02


[[1. 0. 2.]
 [0. 2. 1.]
 [0. 0. 0.]]


Player 1 input:  20


[[1. 0. 2.]
 [0. 2. 1.]
 [1. 0. 0.]]


Player 2 input:  33
Player 2 input:  34
Player 2 input:  10


[[1. 0. 2.]
 [2. 2. 1.]
 [1. 0. 0.]]


Player 1 input:  12
Player 1 input:  21


[[1. 0. 2.]
 [2. 2. 1.]
 [1. 1. 0.]]


Player 2 input:  22


[[1. 0. 2.]
 [2. 2. 1.]
 [1. 1. 2.]]


Player 1 input:  22
Player 1 input:  01


[[1. 1. 2.]
 [2. 2. 1.]
 [1. 1. 2.]]
Draw


In [6]:
#main frame of the tic-tac-toe game function version
def tic_tac_toe():
    game_board=np.zeros((3,3))
    previous_inputs=[]
    print(game_board)
    for game_round in range(9):
        if game_round%2==0:
            player=1
        else:
            player=2
        p_input=get_input_(player,previous_inputs)
        previous_inputs.append(p_input[2])
        game_board[p_input[0],p_input[1]]=player
        print(game_board)
        if check_result(game_board,player)==player:
            print("Player {} wins".format(player))
            return player
    print("Draw")
    return 0

In [7]:
tic_tac_toe()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Player 1 input:  11


[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


Player 2 input:  12


[[0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]


Player 1 input:  01


[[0. 1. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]


Player 2 input:  21


[[0. 1. 0.]
 [0. 1. 2.]
 [0. 2. 0.]]


Player 1 input:  00


[[1. 1. 0.]
 [0. 1. 2.]
 [0. 2. 0.]]


Player 2 input:  02


[[1. 1. 2.]
 [0. 1. 2.]
 [0. 2. 0.]]


Player 1 input:  22


[[1. 1. 2.]
 [0. 1. 2.]
 [0. 2. 1.]]
Player 1 wins


1

In [8]:
tic_tac_toe()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Player 1 input:  01


[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Player 2 input:  11


[[0. 1. 0.]
 [0. 2. 0.]
 [0. 0. 0.]]


Player 1 input:  00


[[1. 1. 0.]
 [0. 2. 0.]
 [0. 0. 0.]]


Player 2 input:  02


[[1. 1. 2.]
 [0. 2. 0.]
 [0. 0. 0.]]


Player 1 input:  01
Player 1 input:  10


[[1. 1. 2.]
 [1. 2. 0.]
 [0. 0. 0.]]


Player 2 input:  02
Player 2 input:  20


[[1. 1. 2.]
 [1. 2. 0.]
 [2. 0. 0.]]
Player 2 wins


2